WIP haxe-download

diff --git a/bin/hx-download b/bin/hx-download
--- a/bin/hx-download
+++ b/bin/hx-download
@@ -1,128 +1,138 @@
 #!/bin/bash
 
-ROOT=$(dirname $(readlink -f $0))
-
+ROOT=$(dirname $(readlink -f $0))/..
 BUILD_OS="linux64"
-BUILD_OS2="linux64"
-
 if [[ "$OSTYPE" == "darwin"* ]]; then
-	BUILD_OS="osx"
-	BUILD_OS2="mac"
+	BUILD_OS="mac"
 fi
 
-get_haxe_version () {
-	local OUTDIR="$1"
-	local VERSION=$("$ROOT/../releases/$OUTDIR/haxe" --version)
+VERSION="${BUILD_OS}_569e52e"
 
-	# Append revision for 4.3.0-rc.1 nightlies that were missing it
-	if [ "$VERSION" = "4.3.0-rc.1" ]; then
-		REV=$(echo "$OUTDIR" | sed -E 's/^haxe_20[0-9]+_([a-f0-9]{5,})\/$/\1/')
-		if [ ! -z "$REV" ] && [ ! "$REV" = "$OUTDIR" ]; then
-			VERSION="$VERSION+$REV"
-		fi
-	fi
+HAXE_STD_PATH=$ROOT/build/$VERSION/std $ROOT/build/$VERSION/haxe --cwd $ROOT run-download.hxml $@
 
-	echo "$VERSION"
-}
+# ROOT=$(dirname $(readlink -f $0))
 
-if [ -z "$1" ]; then
-	echo "hx-download: missing argument(s)"
-	echo ""
-	echo "Usage: hx-download <VERSION> [AS_NAME]"
-	echo "       Download official release VERSION (e.g., 4.3.0)"
-	echo "       Save as AS_NAME if provided or use version number"
-	echo ""
-	echo "   or: hx-download latest [AS_NAME]"
-	echo "       Download latest nightly"
-	echo "       Save as AS_NAME if provided or use version number (with revision)"
-	echo ""
-	echo "   or: hx-download nightly <VERSION> [AS_NAME]"
-	echo "   or: hx-download aws <VERSION> [AS_NAME]"
-	echo "       Download specific nightly VERSION (e.g., 2023-01-22_development_dd5e467)"
-	echo "       Save as AS_NAME if provided or use version number (with revision)"
-	exit 1
+# BUILD_OS="linux64"
+# BUILD_OS2="linux64"
 
-# Download latest nightly
-elif [ "$1" = "latest" ]; then
-	TARGET=$2
+# if [[ "$OSTYPE" == "darwin"* ]]; then
+# 	BUILD_OS="osx"
+# 	BUILD_OS2="mac"
+# fi
 
-	if [ -z "$TARGET" ]; then
-		TARGET="dev"
-	fi
+# get_haxe_version () {
+# 	local OUTDIR="$1"
+# 	local VERSION=$("$ROOT/../releases/$OUTDIR/haxe" --version)
 
-	URL="https://build.haxe.org/builds/haxe/$BUILD_OS2/haxe_latest.tar.gz"
-	FILENAME="haxe_latest"
+# 	# Append revision for 4.3.0-rc.1 nightlies that were missing it
+# 	if [ "$VERSION" = "4.3.0-rc.1" ]; then
+# 		REV=$(echo "$OUTDIR" | sed -E 's/^haxe_20[0-9]+_([a-f0-9]{5,})\/$/\1/')
+# 		if [ ! -z "$REV" ] && [ ! "$REV" = "$OUTDIR" ]; then
+# 			VERSION="$VERSION+$REV"
+# 		fi
+# 	fi
 
-# Download a specific nightly
-elif [ "$1" = "nightly" ] || [ "$1" = "aws" ]; then
-	TARGET=$3
+# 	echo "$VERSION"
+# }
 
-	if [ -z "$TARGET" ]; then
-		TARGET=$2
-	fi
+# if [ -z "$1" ]; then
+# 	echo "hx-download: missing argument(s)"
+# 	echo ""
+# 	echo "Usage: hx-download <VERSION> [AS_NAME]"
+# 	echo "       Download official release VERSION (e.g., 4.3.0)"
+# 	echo "       Save as AS_NAME if provided or use version number"
+# 	echo ""
+# 	echo "   or: hx-download latest [AS_NAME]"
+# 	echo "       Download latest nightly"
+# 	echo "       Save as AS_NAME if provided or use version number (with revision)"
+# 	echo ""
+# 	echo "   or: hx-download nightly <VERSION> [AS_NAME]"
+# 	echo "   or: hx-download aws <VERSION> [AS_NAME]"
+# 	echo "       Download specific nightly VERSION (e.g., 2023-01-22_development_dd5e467)"
+# 	echo "       Save as AS_NAME if provided or use version number (with revision)"
+# 	exit 1
 
-	URL="https://build.haxe.org/builds/haxe/$BUILD_OS2/haxe_$2.tar.gz"
-	FILENAME="haxe_$2"
+# # Download latest nightly
+# elif [ "$1" = "latest" ]; then
+# 	TARGET=$2
 
-# Install a local release file
-# Technically not a download, and potentially unsafe, but can be of use
-# Not documented on purpose
-elif [ -f "$1" ]; then
-	FILE=$(realpath "$1")
+# 	if [ -z "$TARGET" ]; then
+# 		TARGET="dev"
+# 	fi
 
-	# TODO make sure this looks good
-	OUTDIR=$(tar -tf "$FILE" | head -n 1)
+# 	URL="https://build.haxe.org/builds/haxe/$BUILD_OS2/haxe_latest.tar.gz"
+# 	FILENAME="haxe_latest"
 
-	cd "$ROOT/../releases"
-	tar -xf $FILE
-	cd - > /dev/null
+# # Download a specific nightly
+# elif [ "$1" = "nightly" ] || [ "$1" = "aws" ]; then
+# 	TARGET=$3
 
-	TARGET=$2
-	if [ -z "$TARGET" ]; then
-		TARGET="$(get_haxe_version "$OUTDIR")"
-	fi
+# 	if [ -z "$TARGET" ]; then
+# 		TARGET=$2
+# 	fi
 
-	unlink "$ROOT/../versions/$TARGET" 2> /dev/null
-	ln -s "$ROOT/../releases/$OUTDIR" "$ROOT/../versions/$TARGET"
+# 	URL="https://build.haxe.org/builds/haxe/$BUILD_OS2/haxe_$2.tar.gz"
+# 	FILENAME="haxe_$2"
 
-	echo "Installed version $TARGET"
-	exit 0;
+# # Install a local release file
+# # Technically not a download, and potentially unsafe, but can be of use
+# # Not documented on purpose
+# elif [ -f "$1" ]; then
+# 	FILE=$(realpath "$1")
 
-# Install an official release
-else
-	TARGET=$2
+# 	# TODO make sure this looks good
+# 	OUTDIR=$(tar -tf "$FILE" | head -n 1)
 
-	if [ -z "$TARGET" ]; then
-		TARGET=$1
-	fi
+# 	cd "$ROOT/../releases"
+# 	tar -xf $FILE
+# 	cd - > /dev/null
 
-	URL="https://github.com/HaxeFoundation/haxe/releases/download/$1/haxe-$1-$BUILD_OS.tar.gz"
-	FILENAME="haxe-$1-$BUILD_OS"
-fi
+# 	TARGET=$2
+# 	if [ -z "$TARGET" ]; then
+# 		TARGET="$(get_haxe_version "$OUTDIR")"
+# 	fi
 
-cd "$ROOT/../releases"
-rm -f "$FILENAME.tar.gz"
-wget "$URL"
+# 	unlink "$ROOT/../versions/$TARGET" 2> /dev/null
+# 	ln -s "$ROOT/../releases/$OUTDIR" "$ROOT/../versions/$TARGET"
 
-if [ "$?" -eq "0" ]; then
-	OUTDIR=$(tar -tf "$FILENAME.tar.gz" | head -n 1)
-	tar -xf "$FILENAME.tar.gz"
-	rm "$FILENAME.tar.gz"
-	cd - > /dev/null
+# 	echo "Installed version $TARGET"
+# 	exit 0;
 
-	VERSION="$TARGET"
-	if [ "$FILENAME" = "haxe_latest" ] || [ -z "$TARGET" ]; then
-		VERSION="$(get_haxe_version "$OUTDIR")"
-	fi
-	unlink "$ROOT/../versions/$VERSION" 2> /dev/null
-	ln -s "$ROOT/../releases/$OUTDIR" "$ROOT/../versions/$VERSION"
+# # Install an official release
+# else
+# 	TARGET=$2
 
-	if [ "$FILENAME" = "haxe_latest" ]; then
-		unlink "$ROOT/../versions/$TARGET" 2> /dev/null
-		ln -s "$ROOT/../releases/$OUTDIR" "$ROOT/../versions/$TARGET"
-	fi
+# 	if [ -z "$TARGET" ]; then
+# 		TARGET=$1
+# 	fi
 
-	echo "Downloaded version $VERSION"
-else
-	echo "Failed to download $FILENAME"
-fi
+# 	URL="https://github.com/HaxeFoundation/haxe/releases/download/$1/haxe-$1-$BUILD_OS.tar.gz"
+# 	FILENAME="haxe-$1-$BUILD_OS"
+# fi
+
+# cd "$ROOT/../releases"
+# rm -f "$FILENAME.tar.gz"
+# wget "$URL"
+
+# if [ "$?" -eq "0" ]; then
+# 	OUTDIR=$(tar -tf "$FILENAME.tar.gz" | head -n 1)
+# 	tar -xf "$FILENAME.tar.gz"
+# 	rm "$FILENAME.tar.gz"
+# 	cd - > /dev/null
+
+# 	VERSION="$TARGET"
+# 	if [ "$FILENAME" = "haxe_latest" ] || [ -z "$TARGET" ]; then
+# 		VERSION="$(get_haxe_version "$OUTDIR")"
+# 	fi
+# 	unlink "$ROOT/../versions/$VERSION" 2> /dev/null
+# 	ln -s "$ROOT/../releases/$OUTDIR" "$ROOT/../versions/$VERSION"
+
+# 	if [ "$FILENAME" = "haxe_latest" ]; then
+# 		unlink "$ROOT/../versions/$TARGET" 2> /dev/null
+# 		ln -s "$ROOT/../releases/$OUTDIR" "$ROOT/../versions/$TARGET"
+# 	fi
+
+# 	echo "Downloaded version $VERSION"
+# else
+# 	echo "Failed to download $FILENAME"
+# fi
